import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Grafica from './grafica/Grafica.js'
import About from './about/About.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Grafica de Temperatura y Humedad de Incubadora</h1>
        <About />

        <Grafica />

        {console.log("hola vercel")}
      </main>
    </>
  )
}
